kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: {{.Values.route.appname}}
  namespace: {{.Values.route.projectname}}
spec:
  to:
    kind: Service
    name: {{.Values.route.appname}}
    weight: 100
  port:
    targetPort: {{.Values.route.port}}
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
  wildcardPolicy: None
