apiVersion: v1
kind: Service
metadata:
  name: {{.Values.service.appname}}
  namespace: {{.Values.service.projectname}}
spec:
  selector:
    app: {{.Values.service.name}}
  ports:
    - protocol: TCP
      port: {{.Values.service.port}}
      targetPort: {{.Values.service.port}}